"""Add Review Model

Revision ID: f5247359f2a0
Revises: 99b4d20ef624
Create Date: 2025-03-12 23:17:28.319022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5247359f2a0'
down_revision = '99b4d20ef624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
